import { Inter } from "next/font/google";
import { Barlow_Condensed } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Web3ModalProvider from "@/contexts/Web3ModalProvider";
import Navbar from "@/components/Navbar";
import Toolbar from "@/components/Toolbar";
import MusicCard from "@/components/MusicCard";
import AudioPlayer from "@/components/PlayMusicCard";

const inter = Inter({ subsets: ["latin"] });
const barlow = Barlow_Condensed({ subsets: ["latin"], weight: "500" });
const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Web3ModalProvider>
          <div className="flex flex-col">
            <div className="flex">
              <div className="fixed">
                <Navbar />
              </div>

              <div className="absolute left-[250px] flex flex-col">
                <div className="fixed z-10 bg-white">
                  <Toolbar />
                </div>
                {children}
              </div>
            </div>
          </div>
          <div className="fixed bottom-0 ">
            <AudioPlayer />
          </div>
        </Web3ModalProvider>
      </body>
    </html>
  );
}
